### ISSUE TITLE
Removed files are not removed from the database on subsequent scans.

### ISSUE THREAD

**Issue by sixshooterz** [Ewan-Walker/medb#1]
I had many duplicates in my TV Episodes folder. Some with a different file extension, some where there was a slight case difference in the filename (**The** vs **the**). I removed the duplicates but the file scanner did not remove the entry from the database and so the encoder process sees the db entry and tries to convert a non-existent file.

Easy to replicate. Clear the database and intentionally create duplicate files with different file extensions and slight spelling differences.

Run an initial scan.

Close the medb process.

Remove duplicates, leaving only one of each file.

Start medb process and watch the fireworks. :-)

**Comment by ewanwalk** [comment]
Thank you for reporting this!

The issue here is that there is no startup process to validate the database for deleted files, I have implemented a "lazy" method which instead validates if a file exists before being sent to the encoder (as it should).

This should be implemented in 2.0.5 - please let me know if a similar problem persists!
